DELIMITER $$ 
DROP PROCEDURE IF EXISTS BASIC_INSERT;
CREATE PROCEDURE BASIC_INSERT()
BEGIN
 DECLARE i INT DEFAULT 0;
 DECLARE lo INT DEFAULT 100000;
 WHILE( i < lo) DO
  INSERT INTO test(NAME, email, PASSWORD) 
  VALUES(
   CONCAT("gngsn", i), 
   CONCAT(i, "@email.com"), 
   UUID()
  );
  SET i = i+1;
 END WHILE;
END $$
DELIMITER ;